set_property SRC_FILE_INFO {cfile:C:/consegna/vivado/quadrature_encoder/quadrature_encoder.srcs/constrs_1/new/Zybo_Z7_Master.xdc rfile:../../../quadrature_encoder.srcs/constrs_1/new/Zybo_Z7_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V12   IOSTANDARD LVCMOS33 } [get_ports { channelA }]; #IO_L4P_T0_34 Sch=je[1]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W16   IOSTANDARD LVCMOS33 } [get_ports { channelB }]; #IO_L18N_T2_34 Sch=je[2]
