# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/consegna/quadrature_encoder/quadrature_encoder.srcs/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/design_1_PmodOLEDrgb_0_1.xci
# IP: The module: 'design_1_PmodOLEDrgb_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0} -quiet] -quiet

# IP: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_gpio_0_1 || ORIG_REF_NAME==PmodOLEDrgb_axi_gpio_0_1} -quiet] -quiet

# IP: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_pmod_bridge_0_0/PmodOLEDrgb_pmod_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_pmod_bridge_0_0 || ORIG_REF_NAME==PmodOLEDrgb_pmod_bridge_0_0} -quiet] -quiet

# XDC: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_ooc.xdc

# XDC: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_gpio_0_1 || ORIG_REF_NAME==PmodOLEDrgb_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1_ooc.xdc

# XDC: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_gpio_0_1 || ORIG_REF_NAME==PmodOLEDrgb_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_pmod_bridge_0_0/PmodOLEDrgb_pmod_bridge_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_pmod_bridge_0_0 || ORIG_REF_NAME==PmodOLEDrgb_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/design_1_PmodOLEDrgb_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodOLEDrgb_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/consegna/quadrature_encoder/quadrature_encoder.srcs/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/design_1_PmodOLEDrgb_0_1.xci
# IP: The module: 'design_1_PmodOLEDrgb_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0} -quiet] -quiet

# IP: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_gpio_0_1 || ORIG_REF_NAME==PmodOLEDrgb_axi_gpio_0_1} -quiet] -quiet

# IP: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_pmod_bridge_0_0/PmodOLEDrgb_pmod_bridge_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_pmod_bridge_0_0 || ORIG_REF_NAME==PmodOLEDrgb_pmod_bridge_0_0} -quiet] -quiet

# XDC: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_ooc.xdc

# XDC: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_gpio_0_1 || ORIG_REF_NAME==PmodOLEDrgb_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1_ooc.xdc

# XDC: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_gpio_0_1 || ORIG_REF_NAME==PmodOLEDrgb_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_pmod_bridge_0_0/PmodOLEDrgb_pmod_bridge_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_pmod_bridge_0_0 || ORIG_REF_NAME==PmodOLEDrgb_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: c:/consegna/quadrature_encoder/quadrature_encoder.gen/sources_1/bd/design_1/ip/design_1_PmodOLEDrgb_0_1/design_1_PmodOLEDrgb_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodOLEDrgb_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
